[package]
edition = "2021"
name = "indicator-extractor"
version = "0.1.0"

[dependencies]
nom = "7.1.3"
pdf-extract = { version = "0.7.0", optional = true }
tldextract = "0.6.0"
ureq = { version = "2.10.1", optional = true }

[features]
pdf = ["pdf-extract"]
website = ["ureq"]
